name: Pull Request demo

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run: echo "Running tests..."
        
      - name: run linter
        run: echo "Running linter..."